name: build

on:
  workflow_dispatch:

jobs:
  name: build-linux-sse-debug
  runs-on: ubuntu-22.04
  steps:
  - uses: actions/checkout@v3
    with:
      submodules: recursive
  - name: build
    run: |
      mkdir -p build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Debug -DFB_ARCH_TYPE=1 ..
      make