name: build
on:
  workflow_dispatch:

jobs:
  build_plugin:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows 10 SSE2 Debug"
            os: windows-2019
            arch_type: 1
            build_type: DEBUG
          - name: "Windows 10 SSE2 Release"
            os: windows-2019
            arch_type: 1
            build_type: RELEASE
          - name: "Windows 10 AVX2 Debug"
            os: windows-2019
            arch_type: 2
            build_type: DEBUG
          - name: "Windows 10 AVX2 Release"
            os: windows-2019
            arch_type: 2
            build_type: RELEASE
          - name: "Ubuntu Latest SSE2 Debug"
            os: ubuntu-latest
            arch_type: 1
            build_type: DEBUG
          - name: "Ubuntu Latest SSE2 Release"
            os: ubuntu-latest
            arch_type: 1
            build_type: RELEASE
          - name: "Ubuntu Latest AVX2 Debug"
            os: ubuntu-latest
            arch_type: 2
            build_type: DEBUG
          - name: "Ubuntu Latest AVX2 Release"
            os: ubuntu-latest
            arch_type: 2
            build_type: RELEASE
          - name: "MacOS 13 Universal Debug"
            os: macos-13
            arch_type: 3
            build_type: DEBUG
          - name: "MacOS 13 Universal Release"
            os: macos-13
            arch_type: 3
            build_type: RELEASE
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DFB_ARCH_TYPE=${{ matrix.arch_type }}
          cmake --build ./build --config ${{ matrix.build_type }}