name: build

on:
  workflow_dispatch:

jobs:
  job_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        type: [Debug, Release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DFB_USE_SSE=1 -DFB_USE_AVX=0 ..
        make