name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
    - name: build-ubuntu-sse-debug
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DFB_USE_SSE=1 -DFB_USE_AVX=0 ..
        make