name: build
on:
  workflow_dispatch:

jobs:
  build_plugin:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows 2022 Debug"
            arch_type: 1
            os: windows-2022
            build_type: DEBUG
          - name: "Windows 2022 RelWithDebInfo"
            arch_type: 1
            os: windows-2022
            build_type: RELWITHDEBINFO
          - name: "Ubuntu 22 Debug"
            arch_type: 1
            os: ubuntu-22.04
            build_type: DEBUG
          - name: "Ubuntu 22 RelWithDebInfo"
            arch_type: 1
            os: ubuntu-22.04
            build_type: RELWITHDEBINFO
          - name: "MacOS 13 Debug"
            arch_type: 2
            os: macos-13
            build_type: DEBUG
          - name: "MacOS 13 RelWithDebInfo"
            arch_type: 2
            os: macos-13
            build_type: RELWITHDEBINFO
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Linux Deps
        if: matrix.os == 'ubuntu-22.04'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt install libfontconfig1-dev libasound2-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libfreetype6-dev libglu1-mesa-dev libjack-jackd2-dev
      - name: Build
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DFB_ARCH_TYPE=${{ matrix.arch_type }}
          cmake --build ./build --config ${{ matrix.build_type }}